version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mern-backend
    ports:
      - "8000:8000"
    environment:
      - MONGOURL=mongodb://mongo:27017/crud-app
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mern-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
