name: CI/CD Pipeline - Docker Build & Deploy to Azure

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: yourdockerhubusername/mern-backend
  FRONTEND_IMAGE: yourdockerhubusername/mern-frontend
  BACKEND_CONTEXT: ./server
  FRONTEND_CONTEXT: ./client

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BACKEND_CONTEXT }}
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.FRONTEND_CONTEXT }}
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest

  deploy-to-azure:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure WebApp for Containers - Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-backend-app-name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: ${{ env.BACKEND_IMAGE }}:latest

      - name: Azure WebApp for Containers - Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-frontend-app-name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          images: ${{ env.FRONTEND_IMAGE }}:latest
